CREATE DATABASE cloudtica;
USE cloudtica;
SHOW TABLES;
SELECT * FROM cloudtica_cleaned_data;

# What  is the total revenue generated by Cloudtica?
SELECT SUM(sales) AS Total_Sales
FROM cloudtica_cleaned_data;

# What is the total profit earned by the company?
SELECT SUM(Profit) AS Total_Profit
FROM cloudtica_cleaned_data;

# Which are the top 5 products to generate the highest revenue?
SELECT Product, SUM(Sales) AS Total_Sales
FROM cloudtica_cleaned_data
GROUP BY Product
ORDER BY Total_Sales DESC
LIMIT 5;

# Who are the top 5 customers to contribute the most revenue?
SELECT Customer, SUM(Sales) AS Total_Sales
FROM cloudtica_cleaned_data
GROUP BY Customer
ORDER BY Total_Sales DESC
LIMIT 5;

# Which industry generates the highest sales?
SELECT Industry, SUM(Sales) AS Total_Sales
FROM cloudtica_cleaned_data
GROUP BY Industry
ORDER BY Total_Sales DESC;

# Which region generates the highest revenue?
SELECT Region, SUM(Sales) AS Total_Sales
FROM cloudtica_cleaned_data
GROUP BY Region
ORDER BY Total_Sales DESC;

# Which product has the highest demand?
SELECT Product, SUM(`Units Sold`) AS Total_Units
FROM cloudtica_cleaned_data
GROUP BY  Product
ORDER BY Total_Units DESC;

# What is the average discount offered on products?
SELECT AVG(Discount) AS Avg_Discount
FROM cloudtica_cleaned_data;

# Which products generates the highest profit?
SELECT Product, SUM(Profit) AS Total_Profit
FROM cloudtica_cleaned_data
GROUP BY Product
ORDER BY Total_Profit DESC;

# Which transactions resulted in a loss?
SELECT Customer, Product, Sales, Profit
FROM cloudtica_cleaned_data
WHERE Profit < 0;

# Which customer segment generates the most revenue?
SELECT Segment, SUM(Sales) AS Total_Sales
FROM cloudtica_cleaned_data
GROUP BY Segment
ORDER BY Total_Sales DESC;
